apiVersion: v2
name: qts
description: QTS Trading System - Quantitative Trading Strategy Engine
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: tawbury
    email: qts@tawbury.com
keywords:
  - qts
  - trading
  - strategy
  - kr-stocks
  - kiwoom
home: https://github.com/tawbury/qts
sources:
  - https://github.com/tawbury/qts
