---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: observer-secrets
  namespace: observer-prod
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgC3zAvhz0FaV/TaRh5uxswevd7/pUTIMcc1NKDQ5OAO5ZeDt74nXBQFP001L2TxFdUi1zUsaQ1OjH6RXuAoZgoFmEIwWWqXQ4JHrzhr7gYbgYzuO+aqbeMbhqtf0yjluVQ5vMc5zVoX3d4P+aLJGfHGZk6i8QkQblYh26PPcbJOQPvHRUHvla+zlf3srTdt8u4RjWRvPD8Y0duXFWhDTOaKI/xs+5D38Pwg5OFas0vvMLpRBXvCKqUB31a7g0vQkDHDJ3O9bq60PKqG6KEnYKxB47EHZYxqhvEsqVyPNkudnKzVHmM39I3Ce6fJTW4bPUO8zPdRyffpEHB3wQ61bIj5Sg9qZaHOoImjF/2Wb+PeRJM4bU0fJ5yBW2ACPe178sho0SWJlUVL5zDRuv2rUiEGxu3KkwTkmZAPbUlfr7O/MESwkE8kXaiD1V8Wb2nuh/bVMb2Xfpq1IL3bAwZNR/0LgetTpY+OYhx5w6rd6kWy7kY3jf55UVg0KkmoqTX1bDWuWDTkdUSh/1d6if4ByHBJ1oiNJM3PSoeA7GqYmmxVYU+LQ1iY3ftXZSt23uZjadsUk83ozZuKQK5aU2RWIKx39zQzpfVw+pn3jjsiWzmZoAOo+2nZfNNyYUQr9rvDHZAc3fYAUnI/BjHyrozSgXvppKoOxvujfhBV+6+FsOoAdyEAct78D8kZnOl3c4RspZ3TP0CU
    POSTGRES_USER: AgCRZ3Nko55zqa10kAyv5+ZFqgjYeXpHB0w+mcqMTqYdzGabd67Ks/gLc5PVEOpfy9KF7moPaj7g/TIoFFig1yb4oQ0aFjSPe3phwHeNqJHxo5bNVTonClK3DfAh7vfO+64E0kn0PRuxlVlh9S4uR4NVCvPcyA7JED+BTl6b4ds7w5NrOAA9SQUQp5BDwA2pEFJY9ZHnX1Pjp5G+OV2RFZ5a1t4tezOrxrY5cRaomTHXgzTPkYgU8KL+0pa5A9IE43DZgwsU1byBBUb6TcD1FWP26tliaYObAh1jM2pCO8hHdbAWFeZ6d6rszBocs+qvAwN6ghvIxVfovucRREyS+OynRgfebro8F1XBXAk0AaFjUb7Tcj/bodMwcuxemjeKmHdM24z4BN0a5xuEvfQbCDPKiDoViXBZeWcwHSCNzYEZ5itU0M1OSfwuv+fQdZzSkMw7s0znXh3CiC1VDP2LDEqQgttGoZdtc1MRq6v2QLTiPDBesvjY/H5hH11sucJO3cQyar9HaCFdWYj3351de17wGIVMF7q5OEcy462FBAVoexCeGJHaCcnH97M44zW6Hs1QAwOUXem28p40a1OlLHBdeEb4QZvFwy4Ud9f0JjxyeqFl4tz6+7SGamzXXGdw/SAsP5CgzSA5DyxqVzc31OrXAgrSZLwdSNR71PP66/2X5i//vnEZEJAjwbx2OanMrqXTPiQ3KTT2og==
  template:
    metadata:
      creationTimestamp: null
      name: observer-secrets
      namespace: observer-prod
    type: Opaque
