{{- range $key, $val := .Values.secrets }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $.Release.Name }}-{{ $key }}-secret
  namespace: {{ $.Release.Namespace }}
spec:
  encryptedData:
    {{- toYaml $val | nindent 4 }}
---
{{- end }}